### ISSUE TITLE
When Porgs Scream at Webpack and Other Stories

### ISSUE THREAD

**Issue by dkundel** [berlinjs/jsconf2018-special#2]
Hey folks 🤗 

I would love to talk about how to get started with hardware hacking as a JavaScript developer :) 

### Abstract
For many web developers the world of hardware is very intimidating. There is no easy way to go back from a broken to a working project state. You break something, you replace it — there is no Ctrl/Cmd + z. However, getting a project to work is incredibly fun and rewarding.

From an API for your coffee machine to a Porg that screams every time your Webpack build fails to playing games with hundreds of people at the same time, the only limit is your imagination*.

You might not leave this talk with a degree in Electrical Engineering**, but you'll learn useful basics to help you enter the wonderful world of hardware. We'll look at different ways to combine JavaScript and hardware, from APIs all the way to JS enabled microcontrollers. All tied up with some live demos. At the end you won't be able to wait to start your own hardware adventure!

*and maybe your patience
**unless you already have one

**Comment by rmehner** [comment]
:wave:

Sorry for the delay, flu ping pong with the wife isn't the most fun game to play. Unfortunately your talk didn't quite make it. We only have four slots and since it's an evening event, we can't add more slots or it would turn into a night event ;)

However, your talk sounds super fun and I love seeing JavaScript being used in some creative ways, so there are two, not mutually exclusive, options:

1. We'll have a lightning talk section at the event, so maybe you can do a quick 5 minute thing of that talk.

2. Since you're based in Berlin, there's always a regular BerlinJS event :) If you want, I can put you on our waitlist and will get back to you.

Thanks again for proposing.

**Comment by dkundel** [comment]
Hey Robin!

Hope you are better now! I'm happy to do a more elaborate talk another time but I'm also happy to bring my Porg and do a quick 5 minute lightning talk. So maybe both if you are not opposed to it? Especially given how long it typically takes to get a slot arranged between you and me 😄 

Cheers,
Dominik

**Comment by rmehner** [comment]
Let's do both then, I kinda announced you already anyway :D

As for regular meetup: Let's talk after the whole wwwtf thing is done, but I already put you in our talk pipeline trello thingie.
